version: '3.3'

services:
  db-service:
    container_name: geopocket-db
    image: mysql:8.0.19
    networks:
      - geopocket-network
    restart: always
    environment:
      MYSQL_DATABASE: 'geopocket'
      MYSQL_USER: 'geopocket'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '53306:3306'
    volumes:
      - mysql:/var/lib/mysql
  web-service:
    container_name: geopocket
    image: pablobenitogonzalez/geopocket-uoc:latest
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    networks:
      - geopocket-network
    restart: always
    depends_on:
      - db-service

networks:
  geopocket-network:
    driver: bridge
volumes:
  mysql: