edu:
  uoc:
    geopocket:
      security:
        enabled: true

spring:
  profiles:
    active: h2

---
spring:
  profiles: h2
  liquibase:
    enabled: true
    user: a
    password: a
    change-log: classpath:/db/liquibase-changelog.yaml
  datasource:
    url: jdbc:h2:mem:geopocket;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: a
    password: a
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  profiles: local
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase-changelog.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/geopocket?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: geopocket
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  profiles: docker
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase-changelog.yaml
  datasource:
    url: jdbc:mysql://db-service:3306/geopocket?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: geopocket
    password: password
  jpa:
    hibernate:
      ddl-auto: validate