edu:
  uoc:
    geopocket:
      security:
        enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:geopocket;MODE=MySQL
    username: a
    password: a
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/geopocket
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
