edu:
  uoc:
    geopocket:
      security:
        enabled: true

spring:
  profiles:
    active: h2

---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:geopocket;MODE=MySQL
    username: a
    password: a
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/geopocket?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: geopocket
    password: password
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db-service:3306/geopocket?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: geopocket
    password: password
  jpa:
    hibernate:
      ddl-auto: update